catalogue/urls.py
"""reservations.catalogue URL Configuration
"""
from django.urls import path

from . import views

app_name='catalogue'

urlpatterns = [
    path('artist/', views.artist.index, name='artist_index'),
    path('artist/create/', views.artist.create, name='artist_create'),
    path('artist/<int:artist_id>', views.artist.show, name='artist_show'),
    path('artist/<int:artist_id>/edit/', views.artist.edit, name='artist_edit'),
    path('artist/<int:artist_id>/delete', views.artist.delete, name='artist_delete'),
    path('type/', views.type.index, name='type_index'),
    path('type/<int:type_id>', views.type.show, name='type_show'),
    path('locality/', views.locality.index, name='locality_index'),
    path('locality/<int:locality_id>', views.locality.show, name='locality_show'),
    path('role/', views.role.index, name='role_index'),
    path('role/<int:role_id>', views.role.show, name='role_show'),
    path('location/', views.location.index, name='location_index'),
    path('location/<int:location_id>', views.location.show, name='location_show'),
    path('show/', views.show_detail.index, name='show_index'),
    path('show/<int:show_id>', views.show_detail.show, name='show_show'),
    path('representation/', views.representation.index, name='representation_index'),
    path('representation/<int:representation_id>', views.representation.show, name='representation_show'),
    path('', views.base.home, name='home'),
]

reservations/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('catalogue.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Configure Admin Titles
admin.site.site_header = "reservations Administration Page"
admin.site.site_title = "Browser Title"
admin.site.index_title = "Welcome To The Addmin Area..."

catalogue/models/artist.py
from django.db import models
from .type import *

# Create your models here.
class Artist(models.Model):
	firstname = models.CharField(max_length=60)
	lastname = models.CharField(max_length=60)
	types = models.ManyToManyField(Type, through='ArtistType')

	def __str__(self):
		return f"{self.firstname} {self.lastname}"
	
class Meta:
	db_table = "artists"

catalogue/models/artisttype.py
from django.db import models
from .artist import Artist
from .type import Type
from .show import *



class ArtistType(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    

    class Meta:
        db_table = "artist_type"

catalogue/models/artisttypeshow.py
from django.db import models
from .artisttype import ArtistType
from .show import Show

class ArtistTypeShow(models.Model):
    artist_type = models.ForeignKey(ArtistType, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

   

    class Meta:
        db_table = 'artist_type_show'

catalogue/models/locality.py
from django.db import models

# Create your models here.
class Locality(models.Model):
	postal_code = models.CharField(max_length=6)
	locality = models.CharField(max_length=60)
	
	class Meta:
		db_table = "localities"

catalogue/models/location.py
from django.db import models
from .locality import *

# Create your models here.
class Location(models.Model):
	slug = models.CharField(max_length=60, unique=True)
	designation = models.CharField(max_length=60)
	address = models.CharField(max_length=255)
	locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True, related_name='locations')
	website = models.CharField(max_length=255, null=True)
	phone = models.CharField(max_length=30, null=True)
	
	class Meta:
		db_table = "locations"

catalogue/models/representation.py
from django.db import models
from .location import *
from .show import *


# Create your models here.
class Representation(models.Model):
    show = models.ForeignKey(Show, on_delete=models.SET_NULL, null=True, related_name='representations')
    schedule = models.DateTimeField(auto_now_add=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, related_name='representations')

    class Meta:
        db_table = "representations"

catalogue/models/representationuser.py
from django.db import models
from .representation import Representation
from .user import User

class RepresentationUser(models.Model):
    representation = models.ForeignKey(Representation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    places = models.IntegerField()

    class Meta:
        db_table = 'representation_user'

catalogue/models/reservation.py
from django.db import models
from .representation import Representation
from .user import User

class Reservation(models.Model):
    representation = models.ForeignKey(Representation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    places = models.IntegerField()

    class Meta:
        db_table = 'reservations'

catalogue/models/role.py
from django.db import models
from .user import User

# Create your models here.
class Role(models.Model):
	role = models.CharField(max_length=30)
	user = models.ManyToManyField(User, through='RoleUser')
	
	class Meta:
		db_table = "roles"

catalogue/models/roleuser.py
from django.db import models
from .role import Role
from .user import User

class RoleUser(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'role_user'


catalogue/models/shouw.py
from django.db import models
from .location import *

# Create your models here.
class Show(models.Model):
    slug = models.CharField(max_length=60, unique=True)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255, null=True)
    posterUrl = models.CharField(max_length=255, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, related_name='shows')
    bookable = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "shows"

catalogue/models/show.py
from django.db import models
from .location import *
from .artisttype import ArtistType

# Create your models here.
class Show(models.Model):
    slug = models.CharField(max_length=60, unique=True)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255, null=True)
    poster_url = models.CharField(max_length=255, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, related_name='shows')
    bookable = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    artist_types = models.ManyToManyField(ArtistType, through='ArtistTypeShow')

    class Meta:
        db_table = "shows"

def __str__(self):
        return f"{self.title} ({self.location})"

catalogue/models/type.py
from django.db import models
from .artist import *

# Create your models here.
class Type(models.Model):
	type = models.CharField(max_length=60)
	artists = models.ManyToManyField('catalogue.Artist', through='ArtistType')

	def __str__(self):
		return f"{self.type}"
	
	class Meta:
		db_table = "types"

catalogue/models/user.py
from django.db import models


#Create your models here.
class User(models.Model):
    login = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=225)
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)
    email = models.EmailField('Email Address', null=True)
    langue = models.CharField(max_length=2)
    
class  Meta:
	db_table = 'users'


catalogue/forms.py
from django import forms
from catalogue.models import Artist

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['firstname', 'lastname']

class ArtistDeleteForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = []

catalogue/views/artist.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404

from catalogue.models import Artist
from catalogue.forms import ArtistForm, ArtistDeleteForm


# Create your views here.
def index(request):
    artists = Artist.objects.all()

    title = 'Liste des artistes'

    return render(request, 'artist/index.html', {
        'artists': artists,
        'title': title
    })


def show(request, artist_id):
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant')

    title = 'Fiche d\'un artiste'

    return render(request, 'artist/show.html', {
        'artist': artist,
        'title': title
    })

def create(request):
    if request.method == 'POST':
        form = ArtistForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalogue:artist_index')
    else:
        form = ArtistForm()

    title = 'Créer un artiste'

    return render(request, 'artist/create.html', {
        'form': form,
        'title': title
    })

def edit(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)

    if request.method == 'POST':
        form = ArtistForm(request.POST, instance=artist)
        if form.is_valid():
            form.save()
            return redirect('catalogue:artist_show', artist_id=artist.id)
    else:
        form = ArtistForm(instance=artist)

    title = 'Modifier un artiste'

    return render(request, 'artist/edit.html', {
        'artist': artist,
        'form': form,
        'title': title
    })
def delete(request, artist_id):
    try:
        artist = Artist.objects.get(id=artist_id)
    except Artist.DoesNotExist:
        raise Http404('Artist inexistant')

    if request.method == 'POST':
        form = ArtistDeleteForm(request.POST, instance=artist)
        if form.is_valid():
            artist.delete()
            return redirect('catalogue:artist_index')
    else:
        form = ArtistDeleteForm(instance=artist)

    title = 'Supprimer un artiste'

    return render(request, 'artist/delete.html', {
        'artist': artist,
        'form': form,
        'title': title
    })

catalogue/views/base.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html', {})

catalogue/views/locality.py
from django.shortcuts import render
from django.http import Http404

from catalogue.models import Locality


# Create your views here.
def index(request):
    localities = Locality.objects.all()

    title = 'Liste des localities'

    return render(request, 'locality/index.html', {
    'localities': localities,
    'title': title
})


def show(request, locality_id):
    try:
        locality = Locality.objects.get(id=locality_id)
    except Locality.DoesNotExist:
        raise Http404('Locality inexistant')

    title = 'Fiche d\'un locality'

    return render(request, 'locality/show.html', {
        'locality': locality,
        'title': title
    })

catalogue/views/location.py
from django.shortcuts import render
from django.http import Http404

from catalogue.models import Location


# Create your views here.
def index(request):
    locations = Location.objects.all()
    title = 'Liste des lieux de spectacle'

    return render(request, 'location/index.html', {
        'locations': locations,
        'title': title
    })


def show(request, location_id):
    try:
        location = Location.objects.get(id=location_id)
    except Location.DoesNotExist:
        raise Http404('Lieu inexistant')

    title = "Fiche d'un lieu de spectacle"

    return render(request, 'location/show.html', {
        'location': location,
        'title': title
    })

catalogue/views/representation.py
from django.shortcuts import render
from django.http import Http404

from catalogue.models import Representation


# Create your views here.
def index(request):
    representations = Representation.objects.all()
    title = 'Liste des representations'

    return render(request, 'representation/index.html', {
        'representations': representations,
        'title': title
    })


def show(request, representation_id):
    try:
        representation = Representation.objects.get(id=representation_id)
    except Representation.DoesNotExist:
        raise Http404('representation inexistant')

    title = "Fiche d'un representation"

    return render(request, 'representation/show.html', {
        'representation': representation,
        'title': title
    })

catalogue/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <br/>

    {% block content %}

    {% endblock %}
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>





catalogue/templates/home.html
{% extends 'base.html'%}

{% block content %}
    <center>
        <h1> Hello </h1>

        <br/><br/><br/><br/>
        Copyright (c) 2023
    </center>
{% endblock %}

catalogue/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'catalogue:home' %}">Projet Réservation</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalogue:artist_index' %}">Artists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalogue:show_index' %}">Shows</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>